version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: employeedb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - employee_network

volumes:
  postgres_data:

networks:
  employee_network:
    driver: bridge

